tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true

filter:
    excluded_paths:
        - 'tests/*'

build:
    environment:
        php:
            version: 5.5       # Common versions: 5.4.28, 5.5.12, or hhvm
