tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_code_sniffer:
            config:
                standard: "PSR2"

filter:
    excluded_paths:
        - 'tests/*'

build:
    environment:
        php:
            version: 5.5

