tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
            timeout: 300   # How long should we wait for code coverage (in seconds).
            runs: 1        # In how many runs have you split your tests?

filter:
    excluded_paths:
        - 'tests/*'

build:
    environment:
        php:
            version: 5.5.12       # Common versions: 5.4.28, 5.5.12, or hhvm
